### ISSUE TITLE
Salt needs `pciutils` package to work on Debian  

### ISSUE THREAD

**Issue by mickours** [saltstack/salt-bootstrap#165]
The bootstrap works perfectly on Debian but when I run salt-minion I have a warning message about `lspci`.

After an `apt-get install pciutils` there is no more complaint. Maybe this dependency should be add in the Debian part of the script .

**Comment by s0undt3ch** [comment]
Which install type was this? A git install? a stable install?

**Comment by mickours** [comment]
I use the git version exactly as it is describe here https://github.com/saltstack/salt-bootstrap#i-found-a-bug. 
By the way, my system install is a custom install using debootstrap. That's why `pciutils` was not installed, unlike a classical install.

**Comment by s0undt3ch** [comment]
Ok, and what's the error that salt gives you?

**Comment by mickours** [comment]
when I run `salt-minion`I got this message:
`[WARNING ] Error loading grains, unexpected linux_gpu_data output, check that you have a valid shell configured and permissions to run lspci command`

The program does not stop. When I kill it with <Ctr-c> it shows this:
  Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 29, in salt_minion
    minion.start()
  File "/usr/lib/python2.7/dist-packages/salt/**init**.py", line 198, in start
    self.prepare()
  File "/usr/lib/python2.7/dist-packages/salt/**init**.py", line 186, in prepare
    self.minion = salt.minion.Minion(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 450, in **init**
    self.authenticate(timeout, safe)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 833, in authenticate
    creds = auth.sign_in(timeout, safe)
  File "/usr/lib/python2.7/dist-packages/salt/crypt.py", line 282, in sign_in
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 198, in send_auto
    return self.send(enc, load, tries, timeout)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 180, in send
    polled = self.poller.poll(timeout \* 1000)
  File "/usr/lib/python2.7/dist-packages/zmq/sugar/poll.py", line 97, in poll
    return zmq_poll(list(self.sockets.items()), timeout=timeout)
  File "_poll.pyx", line 116, in zmq.core._poll.zmq_poll (zmq/core/_poll.c:1598)
  File "checkrc.pxd", line 11, in zmq.core.checkrc._check_rc (zmq/core/_poll.c:1796)
  KeyboardInterrupt

**Comment by s0undt3ch** [comment]
Well, `pciutils`, which provides `lspci` is only listed as recommends in the the debian packaging, so, I'm not going to add this as a dependency for git installs, sorry.

I will however, open a ticket to see if we can better handle that warning. That traceback is not related to salt bootstrap though, it's a salt issue, could you please open a ticket regarding that in https://github.com/saltstack/salt
