### ISSUE TITLE
bootstrap script adds 'V' in front of branch name when installing with git flag

### ISSUE THREAD

**Issue by travis-hewitt** [saltstack/salt-bootstrap#1910]
### Description of Issue/Question
When using the bootstrap script to install salt from git, the bootstrap script adds a 'v' in front of the version.
For instance, I wanted to install salt from the 3006.x branch.
When I ran the shell script, and looked at the logs, it showed the following. 
This caused the installation to fail. 

`[saltuser@centos tmp]$ sudo sh install_salt.sh -A [redacted ip] -i ssc-e2e-centos-minion-mcm2201540-230153944297 -x python3 -P git 3006.x
 *  INFO: Running version: 2022.10.04
 *  INFO: Executed by: sh
 *  INFO: Command line: 'install_salt.sh -A [redacted ip] -i ssc-e2e-centos-minion-mcm2201540-230153944297 -x python3 -P git 3006.x'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.10.0-1160.25.1.el7.x86_64
 *  INFO:   Distribution: CentOS 7.9

 *  INFO: Installing minion

 *  WARN: Post Neon git based installations will always install salt
 *  WARN: and its dependencies using pip which will be upgraded to
 *  WARN: at least v9.0.1, and, in case the setuptools version is also
 *  WARN: too old, it will be upgraded to at least v9.1

 *  WARN: You have 10 seconds to cancel and stop the bootstrap process...

 *  INFO: Found function install_centos_git_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_centos_git
 *  INFO: Found function install_centos_git_post
 *  INFO: Found function install_centos_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_centos_check_services
 *  INFO: Running install_centos_git_deps()
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos-distro.cavecreek.net
 * epel: codingflyboy.mm.fcix.net
 * extras: mirror.us.oneandone.net
 * updates: linux.mirrors.es.net
Package yum-utils-1.1.31-54.el7_8.noarch already installed and latest version
Package chkconfig-1.7.6-1.el7.x86_64 already installed and latest version
Nothing to do
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos-distro.cavecreek.net
 * epel: codingflyboy.mm.fcix.net
 * extras: mirror.us.oneandone.net
 * updates: linux.mirrors.es.net
Package ca-certificates-2022.2.54-74.el7_9.noarch already installed and latest version
Nothing to do
 *  INFO: Git revision matches a Salt version tag, shallow cloning enabled.
 *  INFO: Attempting to shallow clone v3006.x from Salt's repository https://github.com/saltstack/salt.git
Cloning into 'salt'...
warning: Could not find remote branch v3006.x to clone.
fatal: Remote branch v3006.x not found in upstream origin
 *  WARN: Failed to shallow clone.
 *  INFO: Resuming regular git clone and remote SaltStack repository addition procedure
Unexpected end of command stream
Cloning into 'salt'...`

### Setup
Deploy a fresh VM.

### Steps to Reproduce Issue
1. curl -L https://bootstrap.saltstack.com -o install_salt.sh
2. sh install_salt.sh -i [resource_name] -U -x python3 -P git 3006.x
3. You will find that the bootstrap script adds a 'v' in front of 3006.x

### Versions and Systems
This was found on ubuntu 20, and cent7.

**Comment by garethgreenaway** [comment]
@travis-hewitt This should be resolved in the latest release, can you confirm?  Thanks!

**Comment by travis-hewitt** [comment]
@garethgreenaway this was resolved in the latest release, but as we discussed in slack, the latest bootstrap script fails to install on ubu20.04, giving us these spicy tracebacks:
`ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3108, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2901, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/download.py", line 135, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 382, in _resolve_one
    set(req_to_install.extras) - set(dist.extras)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3064, in extras
    return [dep for dep in self._dep_map if dep]
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3110, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3127, in _compute_dependencies
    common = types.MappingProxyType(dict.fromkeys(reqs_for_extra(None)))
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3124, in reqs_for_extra
    if not req.marker or req.marker.evaluate({'extra': extra}):
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/_vendor/packaging/markers.py", line 245, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/_vendor/packaging/markers.py", line 151, in _evaluate_markers
    groups[-1].append(_eval_op(lhs_value, op, rhs_value))
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/_vendor/packaging/markers.py", line 109, in _eval_op
    return spec.contains(lhs, prereleases=True)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/_vendor/packaging/specifiers.py", line 565, in contains
    normalized_item = _coerce_version(item)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/_vendor/packaging/specifiers.py", line 36, in _coerce_version
    version = Version(version)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: 'cpython'
Failed to download salt dependencies
 *  INFO: Installing Downloaded Salt Dependencies
Processing /tmp/git/deps/contextvars-2.4.tar.gz
Processing /tmp/git/deps/Jinja2-3.1.2-py3-none-any.whl
Processing /tmp/git/deps/MarkupSafe-2.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Processing /tmp/git/deps/PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl
Processing /tmp/git/deps/distro-1.8.0-py3-none-any.whl
Processing /tmp/git/deps/jmespath-1.0.1-py3-none-any.whl
Processing /tmp/git/deps/msgpack-1.0.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Processing /tmp/git/deps/psutil-5.9.5-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Processing /tmp/git/deps/pyzmq-20.0.0-cp38-cp38-manylinux1_x86_64.whl
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3108, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2901, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 382, in _resolve_one
    set(req_to_install.extras) - set(dist.extras)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3064, in extras
    return [dep for dep in self._dep_map if dep]
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3110, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3127, in _compute_dependencies
    common = types.MappingProxyType(dict.fromkeys(reqs_for_extra(None)))
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 3124, in reqs_for_extra
    if not req.marker or req.marker.evaluate({'extra': extra}):
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/_vendor/packaging/markers.py", line 245, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/_vendor/packaging/markers.py", line 151, in _evaluate_markers
    groups[-1].append(_eval_op(lhs_value, op, rhs_value))
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/_vendor/packaging/markers.py", line 109, in _eval_op
    return spec.contains(lhs, prereleases=True)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/_vendor/packaging/specifiers.py", line 565, in contains
    normalized_item = _coerce_version(item)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/_vendor/packaging/specifiers.py", line 36, in _coerce_version
    version = Version(version)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/_vendor/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: 'cpython'
 * ERROR: Failed to run install_ubuntu_git()!!!`

**Comment by dmurphy18** [comment]
Need to check this issue out

**Comment by dmurphy18** [comment]
@travis-hewitt Closing this since the original issue is resolved, and the most recent release 2024-07-16 installs on Ubuntu 20.04 fine
