### ISSUE TITLE
Fails to install  3006.1 from Git on Alma 8

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt-bootstrap#1927]
### Description of Issue/Question
bootstrap install from git with v3006.1 fails due to annotations in looseversion dunder init.

### Setup
Using latest bootstrap 2023.04.26, having failures on Alma 8 which is using Python 3.6 as default python

### Steps to Reproduce Issue
./bootstrap-salt.sh git v3006.1

### Versions and Systems
./bootstrap-salt.sh -- Version 2023.04.26
[root@Unknown tmp]# cat /etc/redhat-release 
AlmaLinux release 8.7 (Stone Smilodon)

Up to date Alma 8.7 as of 2023-05-11
Problem log
```
/usr/lib/python3.6/site-packages/pip/commands/install.py:204: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3.6 install --user` instead.
Processing ./deps/salt-3006.1-py3-none-any.whl
Installing collected packages: salt
Successfully installed salt-3006.1
 *  INFO: Checking if Salt can be imported using python3
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/lib/python3.6/site-packages/salt/__init__.py", line 140, in <module>
    import salt._logging  # isort:skip
  File "/usr/lib/python3.6/site-packages/salt/_logging/__init__.py", line 12, in <module>
    from salt._logging.impl import (
  File "/usr/lib/python3.6/site-packages/salt/_logging/impl.py", line 28, in <module>
    from salt._logging.handlers import DeferredStreamHandler  # isort:skip
  File "/usr/lib/python3.6/site-packages/salt/_logging/handlers.py", line 16, in <module>
    from salt.utils.versions import warn_until_date
  File "/usr/lib/python3.6/site-packages/salt/utils/versions.py", line 18, in <module>
    import looseversion
  File "/usr/lib/python3.6/site-packages/looseversion/__init__.py", line 19
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
 * ERROR: Failed to run install_almalinux_git()!!!
```

This may be a case of cannot use bootstrap install on systems with less than Python 3.7, in which case need to note issue on Install Guild.

**Comment by dmurphy18** [comment]
No problems with Centos 9

**Comment by dmurphy18** [comment]
Closing this as fixed in release of the bootstrap 2024-07-12, see https://github.com/saltstack/salt-bootstrap/actions/workflows/ci.yml.  Please feel free to reopen if other matters relevant to this issue come to light.
