### ISSUE TITLE
Boostrapper to install salt version 2014.1.1 fails to install correctly on Debian Wheezy

### ISSUE THREAD

**Issue by donatello** [saltstack/salt-bootstrap#362]
Here's what I did - booted up a debian wheezy image on EC2 and ran 

```
curl -o salt_install.sh -L http://bootstrap.saltstack.org
sudo sh salt_install.sh git v2014.1.1
```

This appears to work but when I try something simple like:

```
sudo salt-call --local pkg.install at
```

I get (near the end of the output):

```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'pkg_resource.find_changes'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 314, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 144, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 81, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/apt.py", line 415, in install
    return __salt__['pkg_resource.find_changes'](old, new)
KeyError: 'pkg_resource.find_changes'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 82, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/__init__.py", line 314, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 144, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 81, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/apt.py", line 415, in install
    return __salt__['pkg_resource.find_changes'](old, new)
KeyError: 'pkg_resource.find_changes'
```

This is weird because I can't even find the pkg_resource.find_changes code in the salt git repo for this version.

I also tried the same thing with the -P flag - this appears to install a more recent ZMQ besides making dire warnings about debian unstable packages:

```
sh salt_install.sh -P  git v2014.1.1
```

Even with these versions, the same pkg_resource error is returned.

**Comment by s0undt3ch** [comment]
Are you installing on a system that had an older version of salt?

v2014.1.1 does not have a `salt/modules/apt.py`...

**Comment by s0undt3ch** [comment]
No more information was given and we've been bootstrapping debian 7 instance on our jenkins setup.
Closing. Please reopen if need be.

**Comment by vutny** [comment]
@donatello @s0undt3ch I think this could be closed as outdated issue.
