### ISSUE TITLE
Boostrap needs to be updated to support new dep

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt-bootstrap#363]
Now that we have a hard dep on `requests`, boostrap needs to install it or it will blow up when starting the minion:

```
Writing /usr/lib/python2.6/site-packages/salt-2014.1.0_4253_g7cddb64-py2.6.egg-info
 *  INFO: Running install_centos_git_post()
 *  INFO: Running install_centos_check_services()
 *  INFO: Running install_centos_restart_daemons()
Starting salt-minion daemon: Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 6, in <module>
    from salt.scripts import salt_minion
  File "/usr/lib/python2.6/site-packages/salt/__init__.py", line 35, in <module>
    from salt.utils import migrations
  File "/usr/lib/python2.6/site-packages/salt/utils/__init__.py", line 93, in <module>
    import salt.minion
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 60, in <module>
    import salt.client
  File "/usr/lib/python2.6/site-packages/salt/client/__init__.py", line 31, in <module>
    import salt.config
  File "/usr/lib/python2.6/site-packages/salt/config.py", line 28, in <module>
    import salt.pillar
  File "/usr/lib/python2.6/site-packages/salt/pillar/__init__.py", line 13, in <module>
    import salt.fileclient
  File "/usr/lib/python2.6/site-packages/salt/fileclient.py", line 13, in <module>
    import requests
ImportError: No module named requests
[FAILED]
 *  INFO: Running daemons_running()
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
```

**Comment by s0undt3ch** [comment]
The next stable release will have this new hard dependency. Closing as fixed.
