### ISSUE TITLE
salt-bootstrap failing on centos7 deployed using salt-cloud

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt-bootstrap#463]
Here's the traceback:

```
 *  INFO: /bin/sh /tmp/.saltcloud-bbc394d4-ce73-42cd-b296-d42d044f9276/deploy.sh -- Version 2014.07.29

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.10.0-123.el7.x86_64
 *  INFO:   Distribution: CentOS 7.0

 *  INFO: Installing minion
 *  INFO: Found function install_centos_stable_deps
 *  INFO: Found function config_salt
 *  INFO: Found function install_centos_stable
 *  INFO: Found function install_centos_stable_post
[DEBUG   ]  *  INFO: /bin/sh /tmp/.saltcloud-bbc394d4-ce73-42cd-b296-d42d044f9276/deploy.sh -- Version 2014.07.29

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.10.0-123.el7.x86_64
 *  INFO:   Distribution: CentOS 7.0

 *  INFO: Installing minion
 *  INFO: Found function install_centos_stable_deps
 *  INFO: Found function config_salt
 *  INFO: Found function install_centos_stable
 *  INFO: Found function install_centos_stable_post
 *  INFO: Found function install_centos_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_centos_check_services
 *  INFO: Running install_centos_stable_deps()
[DEBUG   ]  *  INFO: Found function install_centos_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_centos_check_services
 *  INFO: Running install_centos_stable_deps()
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1517, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.6/site-packages/salt/states/cloud.py", line 106, in present
    info = __salt__['cloud.create'](cloud_provider, name, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/cloud.py", line 202, in create
    info = client.create(provider, names, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 362, in create
    mapper.create(vm_))
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1163, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/openstack.py", line 775, in create
    ret = salt.utils.cloud.bootstrap(vm_, __opts__)
  File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 420, in bootstrap
    deployed = deploy_script(**deploy_kwargs)
  File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 1208, in deploy_script
    deploy_command
SaltCloudSystemExit: Executing the command '/tmp/.saltcloud-bbc394d4-ce73-42cd-b296-d42d044f9276/deploy.sh -c /tmp/.saltcloud-bbc394d4-ce73-42cd-b296-d42d044f9276' failed

[INFO    ] Completed state [test-coreinfra] at time 15:47:18.297979
nitin-saltmaster:
----------
          ID: test-coreinfra
    Function: cloud.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1517, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/states/cloud.py", line 106, in present
                  info = __salt__['cloud.create'](cloud_provider, name, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/modules/cloud.py", line 202, in create
                  info = client.create(provider, names, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 362, in create
                  mapper.create(vm_))
                File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1163, in create
                  output = self.clouds[func](vm_)
                File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/openstack.py", line 775, in create
                  ret = salt.utils.cloud.bootstrap(vm_, __opts__)
                File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 420, in bootstrap
                  deployed = deploy_script(**deploy_kwargs)
                File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 1208, in deploy_script
                  deploy_command
              SaltCloudSystemExit: Executing the command '/tmp/.saltcloud-bbc394d4-ce73-42cd-b296-d42d044f9276/deploy.sh -c /tmp/.saltcloud-bbc394d4-ce73-42cd-b296-d42d044f9276' failed
     Started: 15:45:06.983851
     Duration: 131314.128 ms
     Changes:   

Summary
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
[root@nitin-saltmaster ~]# 
```

**Comment by s0undt3ch** [comment]
After investigation this is the result in the bad URL for EPEL7, fixed in the develop version of the script.

**Comment by nmadhok** [comment]
https://gist.github.com/nmadhok/9034d301de7cdb782154
