### ISSUE TITLE
Fix for adding repositories doesn't work on Linux Mint

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt-bootstrap#532]
On Linux Mint 17, adding repositories won't work:

```
+ add-apt-repository -y ppa:saltstack/salt
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 91, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for LinuxMint/rebecca
```

This is probably related to the already mentioned https://bugs.launchpad.net/linuxmint/+bug/1198751

The easy solution is exporting an environment variable; I added this to `__ubuntu_derivatives_translation()`:

``` shell
    if [ "${match}" != "" ]; then
        case $match in
            "elementary_os")
                _major=$(echo "$DISTRO_VERSION" | sed 's/\.//g')
                ;;
+            "linuxmint")
+                export LSB_ETC_LSB_RELEASE=/etc/upstream-release/lsb-release
+                _major=$(echo "$DISTRO_VERSION" | sed 's/^\([0-9]*\).*/\1/g')
                ;;
            *)
                _major=$(echo "$DISTRO_VERSION" | sed 's/^\([0-9]*\).*/\1/g')
                ;;
        esac
```

Which allows `add-apt-repository` to work! w00t!

**Comment by The-Loeki** [comment]
I'll be happy to make this into a PR as well if you can live with the mentioned fix ;)
