### ISSUE TITLE
Bootstrap fail on Ubuntu 14.04

### ISSUE THREAD

**Issue by cro** [saltstack/salt-bootstrap#566]
Attempted to update a salt-master via bootstrap to the latest 2015.2 branch:

```
[...]
 *  WARN: The git revision being installed does not match a Salt version tag. Shallow cloning disabled
Cloning into 'salt'...
Switched to a new branch '2015.2'
Branch 2015.2 set up to track remote branch 2015.2 from origin.
 *  INFO: Cloning Salt's git repository succeeded
 *  INFO: Running config_salt()
 *  INFO: Running install_ubuntu_git()
2015.2.0rc1-274-gd2e4ac8
running install
Traceback (most recent call last):
  File "setup.py", line 940, in <module>
    setup(distclass=SaltDistribution)
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 972, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 847, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "/usr/lib/python3.4/distutils/cmd.py", line 62, in __init__
    self.initialize_options()
  File "setup.py", line 438, in initialize_options
    if __saltstack_version__.info >= SaltStackVersion.from_name('Boron'):
TypeError: unorderable types: tuple() >= SaltStackVersion()
 * ERROR: Failed to run install_ubuntu_git()!!!
```

**Comment by cro** [comment]
Nevermind, I made the mistake of running this in a virtualenv and python3 was the default python there.

**Comment by s0undt3ch** [comment]
Hmm, should we confirm that we're running on py2 then?

**Comment by cro** [comment]
That might be a good idea, as in the future distros are starting to migrate
to py3 as the default.

This error occurred on Arch, which has already done so.

On Tue, Mar 31, 2015 at 5:14 PM, Pedro Algarvio notifications@github.com
wrote:

> Hmm, should we confirm that we're running on py2 then?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saltstack/salt-bootstrap/issues/566#issuecomment-88279890
> .

## 

_--cro_
C. R. Oldham, Platform Engineer, SaltStack
cr@saltstack.com / 801-564-4673

**Comment by s0undt3ch** [comment]
Follow up in #568
