### ISSUE TITLE
git develop broken in centos6/rhel6/others? due to missing python tornado dep 

### ISSUE THREAD

**Issue by bradthurber** [saltstack/salt-bootstrap#580]
[Hard dependency on python tornado](https://github.com/saltstack/salt/issues/22694) with latest development build of Salt appears to break salt-bootstrap (incl dev version) on at least CentOS 6 and RHEL 6 due to missing python-tornado depdency. 

```
curl -L https://bootstrap.saltstack.com/develop | sudo sh -s -- git develop
...
  File "/usr/lib/python2.6/site-packages/salt/utils/async.py", line 8, in <module>
    import tornado.ioloop
ImportError: No module named tornado.ioloop
[FAILED]
 *  INFO: Running daemons_running()
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
```

Unfortunately, yum install python-tornado isn't sufficient to fix. After yum install python-tornado, salt-bootstrap is as follows

```
 File "/usr/lib/python2.6/site-packages/salt/utils/async.py", line 9, in <module>
    import tornado.concurrent
ImportError: No module named concurrent
[FAILED]
 *  INFO: Running daemons_running()
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
```

On CentOS 6, RHEL 6, yum repo version of python-tornado is 2.2.1-7 - which doesn't appear to include tornado.concurrent. It seems concurrent is in python-tornado 3.0.0+.

**Comment by bradthurber** [comment]
Running the following before bootstrap git develop is a workaround for the issue on CentOS 6 and RHEL 6

```
sudo yum -y install gcc python-devel python-pip;pip install tornado
```

**Comment by nmadhok** [comment]
Breaking for me too when using latest bootstrap script:

```
Writing /usr/lib/python2.6/site-packages/salt-2015.2.0rc2_4737_g1339ee5-py2.6.egg-info
 *  INFO: Running install_red_hat_enterprise_linux_git_post()
 *  INFO: Running install_red_hat_enterprise_linux_restart_daemons()
Starting salt-minion daemon: Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 14, in <module>
    salt_minion()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 106, in salt_minion
    import salt.cli.daemons
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 46, in <module>
    from salt.utils import parsers, ip_bracket
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 26, in <module>
    import salt.config as config
  File "/usr/lib/python2.6/site-packages/salt/config.py", line 39, in <module>
    import salt.utils.sdb
  File "/usr/lib/python2.6/site-packages/salt/utils/sdb.py", line 9, in <module>
    import salt.loader
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 24, in <module>
    import salt.utils.event
  File "/usr/lib/python2.6/site-packages/salt/utils/event.py", line 79, in <module>
    import salt.payload
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 17, in <module>
    import salt.crypt
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 32, in <module>
    import salt.transport.client
  File "/usr/lib/python2.6/site-packages/salt/transport/client.py", line 12, in <module>
    from salt.utils.async import SyncWrapper
  File "/usr/lib/python2.6/site-packages/salt/utils/async.py", line 8, in <module>
    import tornado.ioloop
ImportError: No module named tornado.ioloop
                                                           [FAILED]
Starting salt-master daemon: Traceback (most recent call last):
  File "/usr/bin/salt-master", line 10, in <module>
    salt_master()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 45, in salt_master
    import salt.cli.daemons
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 46, in <module>
    from salt.utils import parsers, ip_bracket
  File "/usr/lib/python2.6/site-packages/salt/utils/parsers.py", line 26, in <module>
    import salt.config as config
  File "/usr/lib/python2.6/site-packages/salt/config.py", line 39, in <module>
    import salt.utils.sdb
  File "/usr/lib/python2.6/site-packages/salt/utils/sdb.py", line 9, in <module>
    import salt.loader
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 24, in <module>
    import salt.utils.event
  File "/usr/lib/python2.6/site-packages/salt/utils/event.py", line 79, in <module>
    import salt.payload
  File "/usr/lib/python2.6/site-packages/salt/payload.py", line 17, in <module>
    import salt.crypt
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 32, in <module>
    import salt.transport.client
  File "/usr/lib/python2.6/site-packages/salt/transport/client.py", line 12, in <module>
    from salt.utils.async import SyncWrapper
  File "/usr/lib/python2.6/site-packages/salt/utils/async.py", line 8, in <module>
    import tornado.ioloop
ImportError: No module named tornado.ioloop
                                                           [FAILED]
 *  INFO: Running daemons_running()
 * ERROR: salt-minion was not found running
 * ERROR: salt-master was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
 * ERROR: salt-master was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
```

Salt get's installed but fails to start since tornado wasn't installed by the bootstrap script and wasn't present on the system.

**Comment by cetanu** [comment]
I'm experiencing this same issue

All I have to do is `easy_install tornado` before starting up the salt-minion and it's fine.

This is on a fresh install of Centos 7.0, Minimal installation

**Comment by s0undt3ch** [comment]
What version of the script are you running?

**Comment by cetanu** [comment]
Well, the commands I'm running are:

```
curl -L https://bootstrap.saltstack.com -o install_salt.sh
sudo sh install_salt.sh git develop
```

That's the latest, right?

**Comment by roder** [comment]
I'm using the `stable` version of the script on Ubuntu 14.04 and I'm getting this error when trying to bootstrap from a git repo:

``` python
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 172, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 70, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2593, in parse_requirements
    raise ValueError("Missing distribution spec", line)
ValueError: ('Missing distribution spec', "'tornado >= 4.0'")
```

**Comment by gibsonje** [comment]
Encountering this problem as well on Ubuntu 14.04.

Edit: Apparently my bootstrap script was outdated, updating it solved this.

**Comment by audleman** [comment]
@gibsonje How did you update your bootstrap script? I only know how to peg a version of salt; I assume it picks up the proper bootstrap script. Is that wrong?

**Comment by gibsonje** [comment]
@audleman It all depends on your setup. I was encountering this issue locally using vagrant and salt. In that setup you specify the path to the bootstrap script.

A snippet of my vagrant file:

```
machine.vm.provision :salt do |salt|
    # Set bootstrap options for Pip-based installation and newer ZMQ.
    # More options at https://docs.saltstack.com/en/latest/topics/tutorials/salt_bootstrap.html#command-line-options
    salt.install_type = :git
    salt.install_args = 'v2015.8.3'
    salt.bootstrap_script = SALT_BOOTSTRAP_PATH
    salt.bootstrap_options = '-P -Z'
    salt.verbose = true
    salt.colorize = true
```

I just re-downloaded the latest bootstrap script from the repository (NOT the develop branch) and it worked. 

If you're using salt-cloud or some other means, you'll have to look into where you're specifying the bootstrap script. It's a shell script that you can pull down.
