### ISSUE TITLE
salt bootstrap script fails to start salt-master or salt-minion on CentOS 6.6

### ISSUE THREAD

**Issue by nmadhok** [saltstack/salt-bootstrap#599]
Notice the `unbound variable` error in `install_salt.sh: line 1150: STABLE_REV: unbound variable` below:

```
root@nitin-salt-python:~$ sudo sh install_salt.sh -M git develop
 *  INFO: PIPED THROUGH install_salt.sh -- Version 2015.05.07
 *  WARN: Running the unstable version of bootstrap-salt.sh

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   2.6.32-504.16.2.el6.x86_64
 *  INFO:   Distribution: CentOS 6.6

 *  INFO: Installing minion
 *  INFO: Installing master
install_salt.sh: line 1150: STABLE_REV: unbound variable
 *  INFO: Found function install_centos_git_deps
 *  INFO: Found function install_centos_git
 *  INFO: Found function install_centos_git_post
 *  INFO: Found function install_centos_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_centos_check_services
 *  INFO: Running install_centos_git_deps()
 *  INFO: Adding SaltStack's COPR repository
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.5ninesolutions.com
 * epel: reflector.westga.edu
 * extras: mirror.cs.vt.edu
 * updates: mirror.us.leaseweb.net
Package yum-utils-1.1.30-30.el6.noarch already installed and latest version
Package chkconfig-1.3.49.3-2.el6_4.1.x86_64 already installed and latest version
```

Also, the script fails to start salt-master and salt-minion:

```
Writing /usr/lib/python2.6/site-packages/salt-2015.5.0_5108_g811564a-py2.6.egg-info
 *  INFO: Running install_centos_git_post()
 *  INFO: Running install_centos_check_services()
 *  INFO: Running install_centos_restart_daemons()
Starting salt-minion daemon:                               [  OK  ]
Starting salt-master daemon: Traceback (most recent call last):
  File "/usr/bin/salt-master", line 10, in <module>
    salt_master()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 47, in salt_master
    master.start()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 150, in start
    self.prepare()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 130, in prepare
    import salt.master
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 21, in <module>
    import Crypto.Random
ImportError: No module named Random
                                                           [FAILED]
 *  INFO: Running daemons_running()
 * ERROR: salt-master was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
 * ERROR: salt-master was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
root@nitin-salt-python:~$ 
```

**Comment by JordanP** [comment]
Same here :(

```
cloud-init[1293]: *  INFO: System Information:
cloud-init[1293]: *  INFO:   CPU:          GenuineIntel
cloud-init[1293]: *  INFO:   CPU Arch:     x86_64
cloud-init[1293]: *  INFO:   OS Name:      Linux
cloud-init[1293]: *  INFO:   OS Version:   3.10.0-123.9.3.el7.x86_64
cloud-init[1293]: *  INFO:   Distribution: CentOS 7.0
cloud-init[1293]: * DEBUG: Binaries will be searched using the following $PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
cloud-init[1293]: *  INFO: Installing minion
cloud-init[1293]: *  INFO: Installing master
cloud-init[1293]: sh: line 1150: STABLE_REV: unbound variable
```

I called the bootstrap script with `-F -M -D -i supervisor -A 192.168.200.134 git 2014.7`
