### ISSUE TITLE
Bootstrap install of 2015.8.0rc2 fails on CentOS 6.6

### ISSUE THREAD

**Issue by benhosmer** [saltstack/salt-bootstrap#643]
Related possible to #639 too, although the solution from that case didn't fix it for me:

```
Starting salt-master daemon: Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.6/site-packages/salt/scripts.py", line 47, in salt_master
    master.start()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 150, in start
    self.prepare()
  File "/usr/lib/python2.6/site-packages/salt/cli/daemons.py", line 131, in prepare
    self.master = salt.master.Master(self.config)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 329, in __init__
    SMaster.__init__(self, opts)
  File "/usr/lib/python2.6/site-packages/salt/master.py", line 100, in __init__
    self.master_key = salt.crypt.MasterKeys(self.opts)
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 205, in __init__
    self.key = self.__get_keys()
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 263, in __get_keys
    self.opts.get('user'))
  File "/usr/lib/python2.6/site-packages/salt/crypt.py", line 88, in gen_keys
    gen = RSA.generate(bits=keysize, e=65537)
NameError: global name 'RSA' is not defined
```

**Comment by benhosmer** [comment]
Quite likely related to: https://github.com/saltstack/salt/issues/25502

**Comment by benhosmer** [comment]
The solution from https://github.com/saltstack/salt/issues/25502 solved this for me:

```
yum erase -y  python-crypto
yum install -y   python-crypto2.6   # make sure epel is installed
ln -s /usr/lib64/python2.6/site-packages/pycrypto-2.6.1-py2.6-linux-x86_64.egg/Crypto /usr/lib64/python2.6/site-packages/
```

**Comment by s0undt3ch** [comment]
Yep! We need a newer packaged pycrypto. It's going to be packaged and made available by SaltStack.

**Comment by benhosmer** [comment]
Is anyone assigned or working on that actively right now? I assume we only need this for 6, since 7 installed fine for me. I'd be willing to help out with that if no one is actively working on it. You're talking about a COPR repo too correct?

**Comment by s0undt3ch** [comment]
By the time Beryllium is out, so will be the dependency chain in a SaltStack hosted repository.

**Comment by benhosmer** [comment]
So, at the risk of being told "when it's ready", what's the estimate for Beryllium?
