### ISSUE TITLE
not working with salt-cloud shows unknown locale error

### ISSUE THREAD

**Issue by AmitChotaliya** [saltstack/salt-bootstrap#645]
I am using salt-cloud to create instances and passing a specific version for salt-minion as script argument.

``` yaml
staging2-frontline:
  provider: aws
  image: ami-408c7f28
  size: m1.small
  securitygroup:
    - Staging-Global
    - Staging-FrontLine
  tag:
      circle: staging2
      type: frontline
  script: bootstrap-salt
  script_args: stable 2015.5
```

I am getting the following error.

``` log
* ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
nohup: ignoring input
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 6, in <module>
    from salt.scripts import salt_minion
  File "/usr/lib/python2.7/dist-packages/salt/__init__.py", line 68, in <module>
    __define_global_system_encoding_variable__()
  File "/usr/lib/python2.7/dist-packages/salt/__init__.py", line 42, in __define_global_system_encoding_variable__
    encoding = locale.getdefaultlocale()[-1]
  File "/usr/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
 * DEBUG: Running salt-minion by hand outputs:
 * DEBUG: DAEMON LOGS for minion:
 * DEBUG: 2015-08-05 14:57:47,477 [salt.cli.daemons ][INFO    ][4367] SeConnection to 10.170.64.36 closed.
tting up the Salt Minion "scrap2"
2015-08-05 14:57:48,624 [salt.minion      ][ERROR   ][4367] Invalid keyword 'str' for variable 'master_type'
2015-08-05 14:57:48,651 [salt.cli.daemons ][INFO    ][4367] The salt minion is shut down
2015-08-05 14:58:00,985 [salt.cli.daemons ][INFO    ][4414] Setting up the Salt Minion "scrap2"
2015-08-05 14:58:01,921 [salt.minion      ][ERROR   ][4414] Invalid keyword 'str' for variable 'master_type'
2015-08-05 14:58:01,922 [salt.cli.daemons ][INFO    ][4414] The salt minion is shut down
```

**Comment by AmitChotaliya** [comment]
I even tried without passing any script args and it still does not work. I used it without passing any script args a month back It worked then.
