### ISSUE TITLE
SmartOS pkgsrc dependency

### ISSUE THREAD

**Issue by johngrasty** [saltstack/salt-bootstrap#649]
Installed 2015.5.3 via bootstrap script. `salt-call pkg.installed tmux` failed. Debug output is below. I resolved that error with `pkgin in py27-cElementTree`

Adding `py27-cElementTree` to [line 4204](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L4204) of the script should fix this.

**Comment by johngrasty** [comment]
Ahhh. I forgot the debug output:

```
[root@owncloud ~]# salt-call -l debug pkg.installed tmux
[DEBUG   ] Reading configuration from /opt/local/etc/salt/minion
[DEBUG   ] Including configuration from '/opt/local/etc/salt/minion.d/99-master-address.conf'
[DEBUG   ] Reading configuration from /opt/local/etc/salt/minion.d/99-master-address.conf
[DEBUG   ] Including configuration from '/opt/local/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /opt/local/etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /opt/local/etc/salt/minion_id: owncloud
[DEBUG   ] Configuration file path: /opt/local/etc/salt/minion
[DEBUG   ] Reading configuration from /opt/local/etc/salt/minion
[DEBUG   ] Including configuration from '/opt/local/etc/salt/minion.d/99-master-address.conf'
[DEBUG   ] Reading configuration from /opt/local/etc/salt/minion.d/99-master-address.conf
[DEBUG   ] Including configuration from '/opt/local/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /opt/local/etc/salt/minion.d/_schedule.conf
[DEBUG   ] Initializing new SAuth for ('/opt/local/etc/salt/pki/minion', 'owncloud', 'tcp://10.0.0.101:4506')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /opt/local/etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /opt/local/etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
[DEBUG   ] Error loading module.tls: ['PyOpenSSL version 0.14 or later must be installed before  this module can be used.']
[DEBUG   ] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command 'npm --version' in directory '/root'
[DEBUG   ] output: 2.11.3
[DEBUG   ] Failed to import module ilo:
Traceback (most recent call last):
  File "/opt/local/lib/python2.7/site-packages/salt/loader.py", line 958, in _load_module
    ), fn_, fpath, desc)
  File "/opt/local/lib/python2.7/site-packages/salt/modules/ilo.py", line 9, in <module>
    import xml.etree.cElementTree as ET
  File "/opt/local/lib/python2.7/xml/etree/cElementTree.py", line 3, in <module>
    from _elementtree import *
ImportError: No module named _elementtree
[DEBUG   ] Could not LazyLoad pkg.installed
'pkg.installed' is not available.
```
