### ISSUE TITLE
Install the salt on Enterprise Suse Linux SP3 after execute the command salt-call state.highstate -l debug 

### ISSUE THREAD

**Issue by joechang316** [saltstack/salt-bootstrap#664]
2015-10-01 12:05:24,542 [salt.loader      ][DEBUG   ][19946] Error loading module.ifttt: IFTTT Secret Key Unavailable, not loading.
2015-10-01 12:05:24,699 [salt.loader      ][DEBUG   ][19946] Error loading module.ipmi: No module named pyghmi.ipmi
2015-10-01 12:05:24,760 [salt.loader      ][DEBUG   ][19946] Error loading module.victorops: No VictorOps api key found.
2015-10-01 12:05:26,562 [salt.loader      ][ERROR   ][19946] Failed to import module tls, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/salt/loader.py", line 1108, in _load_module
    ), fn_, fpath, desc)
  File "/usr/lib64/python2.6/site-packages/salt/modules/tls.py", line 119, in <module>
    import OpenSSL
  File "/usr/lib64/python2.6/site-packages/OpenSSL/**init**.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib64/python2.6/site-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/lib64/python2.6/site-packages/OpenSSL/_util.py", line 7, in <module>
    binding = Binding()
  File "/usr/lib64/python2.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 83, in __init__
    self._ensure_ffi_initialized()
  File "/usr/lib64/python2.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 99, in _ensure_ffi_initialized
    libraries)
  File "/usr/lib64/python2.6/site-packages/cryptography/hazmat/bindings/utils.py", line 72, in build_ffi
    ext_package="cryptography",
  File "/usr/lib64/python2.6/site-packages/cffi/api.py", line 405, in verify
    lib = self.verifier.load_library()
  File "/usr/lib64/python2.6/site-packages/cffi/verifier.py", line 100, in load_library
    self._compile_module()
  File "/usr/lib64/python2.6/site-packages/cffi/verifier.py", line 196, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "/usr/lib64/python2.6/site-packages/cffi/ffiplatform.py", line 38, in compile
    outputfilename = _build(tmpdir, ext)
  File "/usr/lib64/python2.6/site-packages/cffi/ffiplatform.py", line 65, in _build
    raise VerificationError('%s: %s' % (e.__class__.**name**, e))
VerificationError: CompileError: command 'gcc' failed with exit status 1
2015-10-01 12:05:26,573 [salt.loader      ][DEBUG   ][19946] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
2015-10-01 12:05:26,676 [salt.utils.lazy  ][DEBUG   ][19946] LazyLoaded pkg.install
2015-10-01 12:05:26,676 [salt.utils.lazy  ][DEBUG   ][19946] LazyLoaded pkg.installed
2015-10-01 12:05:26,915 [salt.loader      ][DEBUG   ][19946] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located
2015-10-01 12:05:26,953 [salt.utils.lazy  ][DEBUG   ][19946] Could not LazyLoad pkg.ex_mod_init
2015-10-01 12:05:26,954 [salt.state       ][INFO    ][19946] Running state [git] at time 12:05:26.953478

**Comment by isbm** [comment]
Your Python is too old. Please update it to the latest 2.7.8 available. But then you potentially will get the same error from the other side, where python-pygit2 will be required to be compiled through the same cffi. :wink: To fix that, simply remove python-pygit2 completely, or install gcc, python-dev and all related git stuff.

**Comment by isbm** [comment]
@joechang316 anyways, this is _not_ a Salt's problem, but 3rd party packages. We are going to fix this soon in our buildservice.

**Comment by joechang316** [comment]
ok, thanks a lot!
