### ISSUE TITLE
git install ends up with broken build for develop and 2016.3 on smartos

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt-bootstrap#764]
``` bash
[root@test ~]# curl -L https://bootstrap.saltstack.com | sudo sh -s -- git 2016.3
...
[root@test ~]# salt
Traceback (most recent call last):
  File "/opt/local/bin/salt", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3124, in _call_aside
    f(*args, **kwargs)
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in _build_master
    ws.require(__requires__)
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 962, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'futures>=2.0' distribution was not found and is required by salt
```

Someone mentioned this to me on IRC, I checked and it looks to indeed be broken.

**Comment by sjorge** [comment]
`pip install -U futures` fixes it.,

which is very weird as this is in `requirements/base.txt` so it should get installed :confused:

**Comment by BretFisher** [comment]
Same happens with upgrade from 2015.5.6 to 2015.8.7. Install's fine, but receive that error when running salt-minion.

`curl -L https://bootstrap.saltstack.com | sudo sh -s -- -P git v2015.8.7`

**Comment by BretFisher** [comment]
had to do this first so it would work for me:

```
pkgin -y install py27-pip
pip install -U futures
pip install -U tornado
```

**Comment by rallytime** [comment]
Hi @sjorge and @BretFisher Can you give #966 a try? I think that should fix this up for you when passing `-P` in with the git installation. I don't have a SmartOS box handy currently to test this on, but I think that will fix this up nicely for you guys. 

Please let me know if that fixes it for you and if so, we can get that merged in.

**Comment by sjorge** [comment]
@rallytime works for me now.

**Comment by rallytime** [comment]
Excellent!
