### ISSUE TITLE
Bootstrap fails on FreeBSD 10.2

### ISSUE THREAD

**Issue by msiebeneicher** [saltstack/salt-bootstrap#789]
Hi,

it's looks like that the python dependencies changed not a long time ago. Without any changes of the bootstrap scripts we aren't able to install salt under a Vagrant FreeBSD 10.2 box:

``` sh
sh bootstrap_salt.sh
 *  INFO: PIPED THROUGH bootstrap_salt.sh -- Version 2015.11.09

 *  INFO: System Information:
 *  INFO:   CPU:          Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 *  INFO:   CPU Arch:     amd64
 *  INFO:   OS Name:      FreeBSD
 *  INFO:   OS Version:   10.2-RELEASE-p14
 *  INFO:   Distribution: FreeBSD 10.2

 *  INFO: Installing minion
 *  INFO: Found function install_freebsd_10_stable_deps
 *  INFO: Found function install_freebsd_10_stable
 *  INFO: Found function install_freebsd_10_stable_post
 *  INFO: Found function install_freebsd_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running install_freebsd_10_stable_deps()
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
Checking integrity... done (0 conflicting)
The most recent version of packages are already installed
 *  INFO: Running install_freebsd_10_stable()
Updating SaltStack repository catalogue...
SaltStack repository is up-to-date.
All repositories are up-to-date.
Checking integrity... done (0 conflicting)
The most recent version of packages are already installed
 *  INFO: Running install_freebsd_10_stable_post()
 *  INFO: Running install_freebsd_restart_daemons()
Starting salt_minion.
Traceback (most recent call last):
  File "/usr/local/bin/salt-minion", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3124, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 962, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'msgpack-python>0.3' distribution was not found and is required by salt
/usr/local/etc/rc.d/salt_minion: WARNING: failed to start salt_minion
 *  INFO: Running daemons_running()
 * ERROR: salt-minion was not found running
 * ERROR: Failed to run daemons_running()!!!
 * ERROR: salt-minion was not found running. Pass '-D' to bootstrap-salt.sh when bootstrapping for additional debugging information...
```

After a manual installation of `py27-msgpack-python-0.4.7` the minion could start and everything worked fine again:

``` sh
pkg install py27-msgpack-python-0.4.7

sh bootstrap_salt.sh
 *  INFO: PIPED THROUGH bootstrap_salt.sh -- Version 2015.11.09

 *  INFO: System Information:
 *  INFO:   CPU:          Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 *  INFO:   CPU Arch:     amd64
 *  INFO:   OS Name:      FreeBSD
 *  INFO:   OS Version:   10.2-RELEASE-p14
 *  INFO:   Distribution: FreeBSD 10.2

 *  INFO: Installing minion
 *  INFO: Found function install_freebsd_10_stable_deps
 *  INFO: Found function install_freebsd_10_stable
 *  INFO: Found function install_freebsd_10_stable_post
 *  INFO: Found function install_freebsd_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running install_freebsd_10_stable_deps()
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
Checking integrity... done (0 conflicting)
The most recent version of packages are already installed
 *  INFO: Running install_freebsd_10_stable()
Updating SaltStack repository catalogue...
SaltStack repository is up-to-date.
All repositories are up-to-date.
Checking integrity... done (0 conflicting)
The most recent version of packages are already installed
 *  INFO: Running install_freebsd_10_stable_post()
 *  INFO: Running install_freebsd_restart_daemons()
Starting salt_minion.
 *  INFO: Running daemons_running()
 *  INFO: Salt installed!
```

**Comment by jfindlay** [comment]
@msiebeneicher, thanks for reporting.  This seems to be fixed on the development version of the script, which will be released this week, so I'm going to close the issue.  If you still have problems after upgrading, you are welcome to reopen.

**Comment by msiebeneicher** [comment]
@jfindlay nice - i will remove our workaround and try it again after the upcoming release. I give you then a feedback if everything working fine in our setup.

**Comment by jfindlay** [comment]
@msiebeneicher, excellent, thanks.

**Comment by msiebeneicher** [comment]
@jfindlay : All changes worked as expected 👍 The only left workaround is now the installation of the ca_root_nss package - thx :)
