### ISSUE TITLE
Not able to bootstrap VMware vcenter OS(SuSE)

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt-bootstrap#941]
### Description of Issue/Question

Not able to bootstrap vcenter OS(SuSE), pls add is as todo/RFE.
### Setup

```
mvc01:~ # cat /etc/SuSE-release
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3
mvc01:~ #
```
### Steps to Reproduce Issue

```
mvc01:~/salt-bootstrap-2016.08.15 # ./bootstrap-salt.sh -D                    
 *  INFO: Running version: 2016.08.15
 *  INFO: Executed by: -
 *  INFO: Command line: './bootstrap-salt.sh -D'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.0.101-0.47.52-default
 *  INFO:   Distribution: SUSE 11

 * DEBUG: Binaries will be searched using the following $PATH: /sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin:/usr/java/jre-vmware/bin:/opt/vmware/bin:/opt/vmware/bin
 *  INFO: Installing minion
 *  INFO: Found function install_suse_11_stable_deps
 * DEBUG: DEPS_INSTALL_FUNC=install_suse_11_stable_deps
 * DEBUG: config_suse_11_stable_salt not found....
 * DEBUG: config_suse_11_salt not found....
 * DEBUG: config_suse_stable_salt not found....
 * DEBUG: config_suse_salt not found....
 *  INFO: Found function config_salt
 * DEBUG: CONFIG_SALT_FUNC=config_salt
 * DEBUG: preseed_suse_11_stable_master not found....
 * DEBUG: preseed_suse_11_master not found....
 * DEBUG: preseed_suse_stable_master not found....
 * DEBUG: preseed_suse_master not found....
 *  INFO: Found function preseed_master
 * DEBUG: PRESEED_MASTER_FUNC=preseed_master
 *  INFO: Found function install_suse_11_stable
 * DEBUG: INSTALL_FUNC=install_suse_11_stable
 *  INFO: Found function install_suse_11_stable_post
 * DEBUG: POST_INSTALL_FUNC=install_suse_11_stable_post
 * DEBUG: install_suse_11_stable_restart_daemons not found....
 *  INFO: Found function install_suse_11_restart_daemons
 * DEBUG: STARTDAEMONS_INSTALL_FUNC=install_suse_11_restart_daemons
 * DEBUG: daemons_running_suse_11_stable not found....
 * DEBUG: daemons_running_suse_11 not found....
 * DEBUG: daemons_running_suse_stable not found....
 * DEBUG: daemons_running_suse not found....
 *  INFO: Found function daemons_running
 * DEBUG: DAEMONS_RUNNING_FUNC=daemons_running
 * DEBUG: install_suse_11_stable_check_services not found....
 * DEBUG: install_suse_11_check_services not found....
 * DEBUG: install_suse_stable_check_services not found....
 *  INFO: Found function install_suse_check_services
 * DEBUG: CHECK_SERVICES_FUNC=install_suse_check_services
 *  INFO: Running install_suse_11_stable_deps()
File '/opensuse/SLE_11_SP3/systemsmanagement:saltstack.repo' not found on medium 'https://repo.saltstack.com/'

Abort, retry, ignore? [a/r/i/? shows all options] (a): a
Abort, retry, ignore? [a/r/i/? shows all options] (a): a
Problem accessing the file at the specified URI:
File '/opensuse/SLE_11_SP3/systemsmanagement:saltstack.repo' not found on medium 'https://repo.saltstack.com/'

Please check if the URI is valid and accessible.
 * ERROR: Failed to run install_suse_11_stable_deps()!!!
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
mvc01:~/salt-bootstrap-2016.08.15 #
```

**Comment by thatch45** [comment]
Sorry about the late reply @tjyang , all or our SLE 11 repos are pegged at SP4, the SP4 packages should install without issue. You don't really need to bootstrap script on SLE as the repos are well formed, just follow the instruction for SLES 11 here:
http://repo.saltstack.com/#suse

We will also fix the bootstrap script to handle older SLES 11 service packs

**Comment by tjyang** [comment]
@thatch45, thanks for the update and info.

One of my 5.5 vc VM appliance is 11SP2, not 11SP4.

```
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 2
```

follow the for 11 and I got the following error

```
Traceback (most recent call last):
  File "/usr/bin/salt-minion", line 26, in <module>
    salt_minion()
  File "/usr/lib64/python2.6/site-packages/salt/scripts.py", line 116, in salt_minion
    import salt.cli.daemons
  File "/usr/lib64/python2.6/site-packages/salt/cli/daemons.py", line 47, in <module>
    from salt.utils import parsers, ip_bracket
  File "/usr/lib64/python2.6/site-packages/salt/utils/parsers.py", line 26, in <module>
    import salt.config as config
  File "/usr/lib64/python2.6/site-packages/salt/config.py", line 40, in <module>
    import salt.utils.sdb
  File "/usr/lib64/python2.6/site-packages/salt/utils/sdb.py", line 9, in <module>
    import salt.loader
  File "/usr/lib64/python2.6/site-packages/salt/loader.py", line 30, in <module>
    import salt.utils.event
  File "/usr/lib64/python2.6/site-packages/salt/utils/event.py", line 82, in <module>
    import salt.payload
  File "/usr/lib64/python2.6/site-packages/salt/payload.py", line 17, in <module>
    import salt.crypt
  File "/usr/lib64/python2.6/site-packages/salt/crypt.py", line 37, in <module>
    import salt.transport.client
  File "/usr/lib64/python2.6/site-packages/salt/transport/client.py", line 12, in <module>
    from salt.utils.async import SyncWrapper
  File "/usr/lib64/python2.6/site-packages/salt/utils/async.py", line 8, in <module>
    import tornado.ioloop
ImportError: No module named tornado.ioloop

```

**Comment by thatch45** [comment]
Looks like tornado is not installed, do you have the repo added to zypper? Is the python-tornado rpm installed?

**Comment by tjyang** [comment]
I will create vmware 5.5 test VM for this testing effort, to avoid messing up my vcenter VMs.
